"""Modelos del inventario de telas, diseños y pedidos

Revision ID: 70678117eaca
Revises: 
Create Date: 2026-10-02 20:45:36.822579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70678117eaca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('codigo_pantone', sa.String(length=30), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('metros_disponibles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disenos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_prenda', sa.String(length=150), nullable=True),
    sa.Column('tallas', sa.String(length=50), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('archivado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diseno_telas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metros_por_unidad', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('diseno_id', sa.Integer(), nullable=False),
    sa.Column('tela_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diseno_id'], ['disenos.id'], ),
    sa.ForeignKeyConstraint(['tela_id'], ['telas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('diseno_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['diseno_id'], ['disenos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('metros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tela_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['tela_id'], ['telas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    op.drop_table('pedidos')
    op.drop_table('diseno_telas')
    op.drop_table('disenos')
    op.drop_table('usuarios')
    op.drop_table('telas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
